baseURL = "https://omanshuthapliyal.github.io/"
languageCode = "en-us"
title = "Omanshu Thapliyal"
theme = "avicenna"

# Your Google analytics code.
googleAnalytics = "UA-144848923-1"
# Your Disqus sortname.
disqusShortname = "https-omanshuthapliyal-github-io-blog"

[params]
  subtitle = "PhD student"
  interests="Statistical methods in estimation & control"
  cv_name= "OmanshuThapliyal_CV.pdf"
  blog="https://omanshuthapliyal.github.io/blog"

[[params.affilation]]
  name = "Purdue University,"
  position = "PhD Student"
  contact = "omanshu[at]purdue.edu"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/omanshuthapliyal"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/omanshu/"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/omanshu"

[[params.introduction.paragraph]]
  text="""Hello!

I am a PhD student in Aeronautics & Astronautics Engineering, affiliated with the [Flight Dynamics & Control/Hybrid Systems Lab](https://sites.google.com/view/fdchsl/home). 
I am being advised by [Prof. Inseok Hwang](https://engineering.purdue.edu/AAE/people/ptProfile?resource_id=1403) and [Prof. Arthur Frazho](https://engineering.purdue.edu/AAE/people/ptProfile?resource_id=1339).

Prior to this, I worked with the [MathWorks Inc.](https://www.mathworks.com) for a little less than a year at Natick, Massachusetts.
I did my MS in Aeronautics & Astronautics Engineering from Purdue University, and BTech in Aerospace Engineering from [IIT Kanpur](https://www.iitk.ac.in/aero/).
   """

[[params.projects]]

[[params.projects.project]]
		name = "Identifying mode confusion in aircraft-pilot interactions"
		description = """Most human-machine interaction systems suffer from the dreaded failure of *automation surprise*. This project aims at predicting automation surprises in safety critical systems such as aircraft-autopilot system; and then proposing possible resolution methods to get rid of the mode mismatch events thus identified. | *Collaborators :* [*Prof. Meeko Oishi*](http://www.unm.edu/~oishi/)*,* [*Vignesh Sivaramakrishnan*](https://hscl.unm.edu/people/vignesh-sivaramakrishnan/)"""
		project_page = ""
		code_link = ""
		blog_link = ""

[[params.projects.project]]

		name = "State estimation subject to  packet losses"
		description  = """The project aimed at studying state estimation subject to random packet dropouts. Addressing different  ways to incorporate this randomness led to two different subproblems:

(i) *packet losses are Markovian in nature:* such packet losses are common in communication channels (such as ethernet). 

(ii) *packet losses that occur within specific regions,* where the regions are themselves distributed according to known priors (such as radar jammers). 

Systematic inclusion of known information about packet losses (Markovian, or state dependent distribution of jammers) leads to an improved accuracy in the baseline Kalman filter, with a comparable computation complexity. | *Collaborator :* [*J. S. Nandiganahalli*](https://sites.google.com/view/fdchsl/members/alumni/ph-d/jayaprakash-suraj-nandiganahalli?authuser=0)"""
		project_page = "https://docs.lib.purdue.edu/dissertations/AAI10684254/"
		code_link = ""
		blog_link = ""

[[params.projects.project]]
		name = "Consensus based hybrid state estiamtion for networked control systems (NCS)"
		description = """This project aimed at extending the idea of consensus based state estimation (such as consensus-Kalman filters) to hybrid state estimators (such as IMM, GPB-I, GPB-II, etc.). The key idea is to allow consensus at each agent of the NCS and include it in a manner that allows for time-changing topologies of the connecting network. The state estimator developed outperforms all consensus based estimators for hybrid systems (as of 2018). | *Collaborators :* [*Raj Deshmukh*](https://sites.google.com/view/fdchsl/members/ph-d-students/raj-deshmukh?authuser=0)*,* [*Cheolhyeon Kwon*](https://sites.google.com/view/fdchsl/members/alumni/post-doc/cheolhyeon-kwon?authuser=0)"""
		project_page = "https://doi.org/10.1049/iet-cta.2017.1208"
		code_link = "https://github.com/raj-13-d/Cyberattack"
		blog_link = ""


[[params.publications]]
  year="Journal Papers"

  [[params.publications.paper]]
    name = "Kalman filtering with state-dependent packet losses"
    authors = "*O Thapliyal, JS Nandiganahalli, I Hwang*"
    dest  = "IET Control Theory & Applications"
    link = "https://doi.org/10.1049/iet-cta.2018.5425"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
    name = "Distributed state estimation for a stochastic linear hybrid system over a sensor network"
    authors = "*R Deshmukh, O Thapliyal, C Kwon, I Hwang*"
    dest  = "IET Control Theory & Applications"
    link = "https://doi.org/10.1049/iet-cta.2017.1208"


[[params.publications]]
  year="Conference Papers"

  [[params.publications.paper]]
		name = "Learning based Cyberattack Design for Partially-known Supervisory Control Systems, [submitted]"
		authors = "*O Thapliyal, I Hwang*"
		dest  = "21st IFAC World Congress, 2020"
		link = "https://www.ifac2020.org/"

  [[params.publications.paper]]
		name = "Predicting Mode Confusion Through Mixed Integer Linear Programming"
		authors = "*V Sivaramakrishnan, O Thapliyal, A Vinod, M Oishi, I Hwang*"
		dest  = "IEEE 58th Annual Conference on Decision and Control, 2019"
		link = "https://cdc2019.ieeecss.org/"


  [[params.publications.paper]]
		name = "Optimal state estimation for LTI systems with imperfect observations"
		authors = "*O Thapliyal, JS Nandiganahalli, I Hwang*"
		dest  = "IEEE 56th Annual Conference on Decision and Control, 2017"
		link = "https://doi.org/10.1109/CDC.2017.8264065"


[[params.hobbies.paragraph]]
   text="""I like to read history books in my spare time. My favourite author is the British historian Lawrence James. At the moment I am reading *[The Rise and Fall of Classical Greece](https://www.amazon.com/Classical-Greece-Princeton-History-Ancient/dp/0691173141)*.


I like playing board games and Dungeons & Dragons with my party. I am currently trying to level up my Half - Elf Bard.

I love live music and try to attend as many concerts as possible. I am especially into classic progressive rock. I also play a little myself. Friends often find me playing my guitar or ukulele before I am forcefully shut down. I am trying to teach myself to play the harmonica these days.

I also play some video games on my Switch & PlayStation from time to time. I am struggling with the Legend of Zelda: BoTW at the moment. If I ***really*** want to waste a day, I fire up a game of Sid Meier's Civilization V/VI.
"""
